blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://gdmongolite.readthedocs.io
    about: Check the documentation for usage examples and API reference
  - name: 💬 Discussions
    url: https://github.com/ganeshdatta23/gdmongolite/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📧 Email Support
    url: mailto:ganeshdattapadamata@gmail.com
    about: Contact the author directly for urgent issues